### ISSUE TITLE
How can we generate import in g.dart file

### ISSUE THREAD

**Issue by bluegearapps** [schultek/super_annotations#1]
Thank you for the great plugin!
How can we create `import` for .g.dart file? i have a bunch of similar imports need to be added to each .g.dart file. Thank you!

**Comment by schultek** [comment]
You can add import directives to your output like this:
```dart
@override
void apply(Class target, LibraryBuilder output) {
  output.directives.add(Directive.import('package:my_package/my_file.dart'));
}
````
