### ISSUE TITLE
Not compatible with analyzer version > 4.6.0

### ISSUE THREAD

**Issue by nblum37** [schultek/super_annotations#4]
Hi,

the package runs into errors, that `visitRecordType` is not implemented in the super_annotations code but is required by the analyzer package.
I used super_annotations 0.5.0, build_runner 2.2.1, and analyzer 5.0.0.

BR :)

**Comment by nblum37** [comment]
Probably, that might be the breaking analyzer commit
https://github.com/dart-lang/sdk/commit/293c39cfce88982c153ed97874d7c6236c6c0289#diff-f6397b179a9bfe39634f47d8fafd58ec5c50d9cf9437f29deeabb3b6504bfb6e

**Comment by schultek** [comment]
Yes seems like an api change. I have to see how to support before and after.

**Comment by schultek** [comment]
Fixed in `v0.6.0`

**Comment by nblum37** [comment]
It works :) Thank you!
