### ISSUE TITLE
Missing getter definitions

### ISSUE THREAD

**Issue by nblum37** [schultek/super_annotations#6]
Hi,

when running the new 0.7.0 I get the following errors. Probably, that is connected to the statical code analysis at pub.dev.

<img width="1235" alt="Bildschirmfoto 2022-10-19 um 01 27 31" src="https://user-images.githubusercontent.com/82163574/196563858-d7d50869-6ea3-431a-9ebb-07172c86ab78.png">

Thank you :)

**Comment by schultek** [comment]
Oh ok. Looks like some deprecation issues with the analyzer. I'll check.

**Comment by schultek** [comment]
Done in `0.7.1`

**Comment by nblum37** [comment]
Seems to work now :)
