### ISSUE TITLE
Add external key word for the FieldBuilder

### ISSUE THREAD

**Issue by XinyuKhan** [schultek/super_annotations#8]
Something like this:

```Dart
class MyStruct externs Struct {
    @Float()
    external double value;
}
```

**Comment by schultek** [comment]
I'm using the [code_builder](https://pub.dev/packages/code_builder) package, there it seems they don't have a external keyword I could use. So you have to open an issue there first.

**Comment by XinyuKhan** [comment]
Thanks for your reply, I also found this in the [code_builder](https://pub.dev/packages/code_builder)  and I posted the same issue there, I used want to add this feature by myself, but I just began to learn dart a week ago. I hope this feature may be added someday. Good luck.
